---
# tasks file for roles/docker

# Add Docker APT repository key
- name: Add Docker APT repository key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true
  become: true

# Get DEB architecture
- name: Get DEB architecture
  ansible.builtin.command: dpkg --print-architecture
  register: our_architecture
  changed_when: false

# Add Docker source
- name: Add Docker source
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ our_architecture.stdout }},signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

# Install Docker and Docker Compose plugin
- name: Install Docker and Docker Compose plugin
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: true
  become: true

# Add vagrant user to docker group
- name: Add vagrant user to docker group
  ansible.builtin.user:
    name: vagrant
    groups: docker
    append: yes
  become: true

# Reset SSH connection
- name: Reset SSH connection
  ansible.builtin.meta: reset_connection
